### ISSUE TITLE
Issues with workaround for responsive max-width glitch when initializing the canvas element

### ISSUE THREAD

**Issue by circlecube** [iliasiovis/Hoverizr#2]
I'm trying to use this script, but only on some images in my site. But for some reason it is setting every img on the site to max-width="100%" as an inline style. Not all are at 100%, some are much smaller and some have px values. It looks like on line 47 you're checking to see if the maxWidth value of all img elements is set to "none" and if not setting all images to maxwidth on line 173.

First it seems like this should only apply to images that apply rather than all img elements. So whatever selector sent in the hoverizr instatiation.

Second, there are more possible values for max-width than 100% and none.

Any suggestions?

**Comment by iliasiovis** [comment]
Hello and really sorry for the delay (swamped in work).

When I first started working on hoverizr, things were pretty simple in responsive web design. Since then, much has changed, and if I were to write hoverizr again I would change a lot of things.

Unfortunately I am really busy nowadays (and for the next few months) so I cannot support hoverizr currently.

On the lines you mentioned, you can add/edit whatever you want to fix the little glitch. 
From what you tell me, you have pretty much figured out the solution!

Feel free to build on it and let me know how it goes 

Really sorry I couldn't help you out right now. (I am leaving the topic open in case you start fixing it and need anything)

**Comment by circlecube** [comment]
Thanks for the update. I had some success working with it but ended up going in a different direction. Now using https://github.com/GianlucaGuarini/jQuery.BlackAndWhite
